### PR TITLE
Support yaml and binding Map in POJO

### PR DESCRIPTION
**Pull request by abhimanyuseth**
Spring does look to bind these externally loaded properties to a POJO. However, there were some additional changes needed to bind the properties as Map in a POJO when using @ConfigurationProperties, and also to load YAML files as Properties.

Firstly, I updated the `build.gradle` file to work with the recent JDK and Gradle versions. Some library dependencies complained, so I updated the versions of all dependencies to the current latest.

To load YAML files, I'm checking the file extension and then using the `YamlPropertiesFactoryBean` to load the YAML as Properties.
Next, for @ConfigurationProperties, Spring wasn't binding Map in the POJO for the S3PropertySource. Turns out, it only does it if the source is fully enumerable - i.e., it extends from EnumerablePropertySource instead of PropertySource.

### CODE REVIEW

**Comment by ericdallo** [comment]
Thank you for the great effort @abhimanyuseth, I'll take some time to read the changes and try to test locally :)

**Comment by abhimanyuseth** [comment]
@ericdallo I was looking to add some IntegrationTests that'll test the POJO binding with ConfigurationProperties with properties and yaml files from S3. Do you mind if I migrate the tests to Junit 5?

**Comment by ericdallo** [comment]
No!
It'd be great to have tests using junit5

**Comment by ericdallo** [comment]
I'm kind of busy, but I'll try to take a look on this PR this weekend

**Review by ericdallo — APPROVED** [review]
It's a really good job, thank you for your contribution!

**Pull request merged**
